---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: nextcloud
helmCharts:
  - name: nextcloud
    releaseName: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 4.3.6
    namespace: nextcloud
    valuesInline:
      ingress:
        enabled: true
        className: nginx
        annotations:
          # Ref. https://artifacthub.io/packages/helm/nextcloud/nextcloud?modal=values
          # Everything under here needs to be set for TLS to work properly in NextCloud
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-http01 # our clusterissuer
          nginx.ingress.kubernetes.io/server-snippet: |-
            server_tokens off;
            proxy_hide_header X-Powered-By;
            rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
            rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
            rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
            rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
            location = /.well-known/carddav {
              return 301 $scheme://$host/remote.php/dav;
            }
            location = /.well-known/caldav {
              return 301 $scheme://$host/remote.php/dav;
            }
            location = /robots.txt {
              allow all;
              log_not_found off;
              access_log off;
            }
            location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
              deny all;
            }
            location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
              deny all;
            }
        tls:
          - hosts:
              - nextcloud.example.com
            secretName: nextcloud-tls
      nextcloud:
        host: nextcloud.example.com
      # Dynamically create a Persistent Volume
      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 8Gi

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: nextcloud
      spec:
        ipFamilies:
        - IPv6
        - IPv4
        ipFamilyPolicy: PreferDualStack
