---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
helmCharts:
  - name: cilium
    releaseName: cilium
    repo: https://helm.cilium.io/
    version: 1.14.4
    namespace: kube-system
    valuesFile: cilium-values.yaml
