---
# https://docs.cilium.io/en/stable/network/bgp-control-plane/#service-announcements
# By default, virtual routers will not announce services. Virtual routers will announce the ingress IPs of any LoadBalancer services that matches the .serviceSelector of the virtual router.
# If you wish to announce ALL services within the cluster, a NotIn match expression with a dummy key and value can be used like:

# ONLY USE THIS WHEN YOU HAVE A ROUTER THAT SUPPORTS BGP
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering-policy
spec:
  #  nodeSelector:
  #    matchLabels:
  #      bgp-policy: a
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: true
      neighbors:
        - peerAddress: "192.168.0.1/32"
          peerASN: 64512
      serviceSelector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
