apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  interfaces:
    - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: false
  #loadBalancerIPs: true
