apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool-1"
spec:
  cidrs:
    - cidr: "192.168.2.0/24"
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx # all other services in the cluster can be of type "ClusterIP" which does not need a LB-ip
