---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - cilium-loadbalancer-ip-pool.yaml
  - cilium-l2-announcement-policy.yaml
