---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  # install cert-manager and related api objects
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
  #- selfsigned-cluster-issuer.yaml
